version: '3'
services:
  app:
    container_name: rest-go-demo
    build: .
    ports:
      - 8080:8080
    restart: on-failure
    volumes:
      - api:/usr/src/app/
    depends_on:
      - mysql
    networks:
      - fullstack

  mysql:
    image: mysql:8.0
    container_name: godockerDB
    ports:
      - 3306:3306
    environment:
      - MYSQL_DATABASE=learning_demo
      - MYSQL_USER=admin
      - MYSQL_PASSWORD=Control123
      - MYSQL_ROOT_PASSWORD=Control123
    volumes:
      - database_mysql:/var/lib/postgresql/data

    networks:
    - fullstack

volumes:
  api:
  database_mysql:

networks:
  fullstack:
    driver: bridge